### ISSUE TITLE
Support Python 3.5

### ISSUE THREAD

**Issue by joshfriend** [heroku/heroku-buildpack-python#246]
https://www.python.org/downloads/release/python-350/

**Comment by youtux** [comment]
+1

**Comment by zupo** [comment]
+1

**Comment by klinkin** [comment]
+1

**Comment by cclauss** [comment]
Hi @klinkin, @zupo, @youtux instead of +1-ing the issue (problem), it would be help us to make progress if you could validate and the +1 the [pull request](https://github.com/heroku/heroku-buildpack-python/pull/250) (proposed solution).  Thanks.

**Comment by youtux** [comment]
Hi @cclauss, how am I supposed to test it? I tried to set the buildpack using:
```
heroku buildpacks:set https://github.com/cclauss/heroku-buildpack-python#8f4ca7f6244f7b692e02af2b9631c9d497aa8d55
```

But I get the following error, probably due to the fact that the compiled `python-3.5.0` is not available on the heroku servers:
```
$ git push heroku master
Counting objects: 6, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (6/6), 547 bytes | 0 bytes/s, done.
Total 6 (delta 0), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Fetching custom git buildpack... done
remote: -----> Python app detected
remote: -----> Installing runtime (python-3.5.0)
remote:  !     Requested runtime (python-3.5.0) is not available for this stack (cedar-14).
remote:  !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
remote:
remote:  !     Push rejected, failed to compile Python app
remote:
remote: Verifying deploy....
remote:
remote: !	Push rejected to ****.
remote:
To https://git.heroku.com/****.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/****.git'
```

**Comment by kennethreitz** [comment]
fixed!

**Comment by ygao2008** [comment]
Hi @kennethreitz 
I'm still getting the same error, do you know why? I'm using the free tier of Heroku if that makes any difference.

(venv) git push heroku master
Counting objects: 20, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (15/15), done.
Writing objects: 100% (20/20), 3.88 KiB | 0 bytes/s, done.
Total 20 (delta 0), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Fetching set buildpack git://github.com/heroku/heroku-buildpack-python.git... done
remote: -----> Python app detected
remote: -----> Installing runtime (Python-3.5.0)
remote:  !     Requested runtime (Python-3.5.0) is not available for this stack (cedar-14).
remote:  !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
remote:
remote:  !     Push rejected, failed to compile Python app
remote:
remote: Verifying deploy....
remote:
remote: !       Push rejected to *.
remote:
To https://git.heroku.com/*.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/*.git'

**Comment by joshfriend** [comment]
@ygao2008 have you tried not capitalizing "python" in `runtime.txt`?

e.g:
```
python-3.5.0
```

**Comment by ygao2008** [comment]
@joshfriend
That was it! It worked after changing to lowercase. Thank you so much!

**Comment by awhillas** [comment]
nope. Still getting this error :( My runtime.txt looks like:

	python-3.5.0

**Comment by awhillas** [comment]
Full error is:

	$ git push heroku master
	Counting objects: 8, done.
	Delta compression using up to 4 threads.
	Compressing objects: 100% (7/7), done.
	Writing objects: 100% (8/8), 803 bytes | 0 bytes/s, done.
	Total 8 (delta 6), reused 0 (delta 0)
	remote: Compressing source files... done.
	remote: Building source:
	remote: 
	remote: -----> Using set buildpack heroku/python
	remote: -----> Python app detected
	remote: -----> Found runtime python-2.7.9, removing
	remote: -----> Installing runtime (python-3.5)
	remote:  !     Requested runtime (python-3.5) is not available for this stack (cedar-14).
	remote:  !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
	remote: 
	remote:  !     Push rejected, failed to compile Python app
	remote: 
	remote: Verifying deploy...
	remote: 
	remote: !	Push rejected to gnarles-stage2.
	remote: 
	To https://git.heroku.com/gnarles-stage2.git
	 ! [remote rejected] master -> master (pre-receive hook declined)
	error: failed to push some refs to 'https://git.heroku.com/gnarles-stage2.git'

**Comment by joshfriend** [comment]
@awhillas check `runtime.txt` again, the buildpack logs you posted clearly say that you requested `python-3.5` instead of `python-3.5.0`.

**Comment by awhillas** [comment]
Nope, i'm sure it was `python-3.5.0`. I switched it back to `python-2.7.9` and I'm still getting the same error :( I'm going to kill the project and start again.

**Comment by addisonhuddy** [comment]
@awhillas did you find a solution. Running into a similar issues.

```
Install Python.
-----> Found python-2.7.11, removing.
-----> Preparing Python runtime (python-3.5.1.)
 !     Requested runtime (python-3.5.1.) was not found.
 !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
```

**Comment by joshfriend** [comment]
@addisonhuddy You need to remove the period from your version string in `runtime.txt`

**Comment by joshfriend** [comment]
@addisonhuddy You need to remove the extra `.` from the end of your version string in `runtime.txt`

Whatever you see between the `()` in the `Preparing Python runtime` message is the version you requested that heroku install. If you have extra characters (like in your case), or omit part of the version (as @awhillas did), it will not work.

**Comment by kennethreitz** [comment]
Yes, exact names only.

**Comment by addisonhuddy** [comment]
@joshfriend sorry for the typo. I have been trying different python versions with no luck.  With a correct `runtime.txt` I still seeing the same error. Thanks in advance for the help.

```
Install Python.
-----> Found python-2.7.11, removing.
-----> Preparing Python runtime (python-3.5.1)
 !     Requested runtime (python-3.5.1) was not found.
 !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
Failed to compile droplet
Exit status 223
```

**Comment by kennethreitz** [comment]
"Failed to compile droplet"? What is a droplet?

**Comment by joshfriend** [comment]
It looks like he may be trying to use this buildpack with CloudFoundary, which [can use Heroku buildpacks](https://docs.cloudfoundry.org/buildpacks/) (which makes sense because their python one was forked from this).

Interestingly, that line of the error message has been edited out of the comments...

**Comment by addisonhuddy** [comment]
I'm testing my app on a variety of PaaS so I removed the line in a effort in reduce confusion. After testing with a few versions of python and buildpacks, its clear the the error is with my app. Thanks for the help.

**Comment by julichitai** [comment]
help me please!
my runtime.txt: python-3.5.2
Python app detected
-----> Found python-2.7.11, removing
-----> Installing python-3.5.2
 !     Requested runtime (python-3.5.2
 !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
 !     Push rejected, failed to compile Python app.
 !     Push failed
How can I fix it?

**Comment by kennethreitz** [comment]
@julichitai it looks like you specified `(python-3.5.2`, instead of `python-3.5.2`

**Comment by RyanSCL** [comment]
+1

**Comment by edmorley** [comment]
@RyanSCL - this buildpack has supported using Python 3.5 since October 2015, which is why this issue is marked as closed and a comment left saying it was fixed (https://github.com/heroku/heroku-buildpack-python/issues/246#issuecomment-146571499).

Looking at your GitHub activity I see you've recently forked [a project](https://github.com/watson-developer-cloud/natural-language-classifier-nodejs) that uses the nodejs buildpack. Note that that buildpack doesn't add any Python binaries (it's for use with nodejs projects after all), so using `python3` in that app will actually refer to the system installed Python ([cedar-14 package list](https://devcenter.heroku.com/articles/cedar-ubuntu-packages)), ie:
```bash
~ $ which python3
/usr/bin/python3
~ $ python3 --version
Python 3.4.3
```

If your project needs multiple language support, you need to use Heroku's [multiple buildpack support](https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app), and have both the nodejs and python buildpacks configured for your app. The Python buildpack will then vendor whichever version of Python you choose into `/app/.heroku/python/bin`.

If that wasn't the problem you were having, please file a separate issue (it's generally best to not comment on the end of an unrelated ticket when reporting problems), and I'm sure someone will be able to help :-)

**Comment by shivangigupta1404** [comment]
I am getting this error
I have checked for all the solutions of this page
no extra "." present at end , all in lowercase
Kindly help me with this problem

```
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Python app detected
remote: -----> Installing "python-2.7.11"
remote:  !     Requested runtime ("python-2.7.11") is not available for this sta
ck (cedar-14).
remote:  !     Aborting.  More info: https://devcenter.heroku.com/articles/pytho
n-support
remote:  !     Push rejected, failed to compile Python app.
remote:
remote:  !     Push failed
remote: Verifying deploy....
remote:
```

**Comment by 4bic** [comment]
@shivangigupta1404 , did you fix the issue? 
Heroku’s Python support extends to the latest stable release from the Python 2.x and Python 3.x series : 
curently , this support extends to these **specific** runtimes:
    

- python-2.7.13

- python-3.6.0

https://devcenter.heroku.com/articles/python-runtimes#supported-python-runtimes

**Comment by shivangigupta1404** [comment]
@4bic the mistake I found out was that i dint include the required python packages in requirement.txt.
That solved my problem.

**Comment by qutaken** [comment]
me meet too!

all error : Counting objects: 49, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (40/40), done.
Writing objects: 100% (49/49), 11.80 KiB | 0 bytes/s, done.
Total 49 (delta 3), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Python app detected
remote:  !     Warning: Your application is missing a Procfile. This file tells Heroku how to run your application.
remote:  !     Learn more: https://devcenter.heroku.com/articles/procfile
remote:  !     The latest version of Python 3 is python-3.6.3 (you are using python-3.5.0, which is unsupported).
remote:  !     We recommend upgrading by specifying the latest version (python-3.6.3).
remote:        Learn More: https://devcenter.heroku.com/articles/python-runtimes
remote: -----> Installing python-3.5.0
remote:  !     Requested runtime (python-3.5.0) is not available for this stack (heroku-16).
remote:  !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
remote:  !     Push rejected, failed to compile Python app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to quiet-tor-36783.
remote:

**Comment by shivangigupta1404** [comment]
@qutaken inside your app directory run following commands

`echo web:gunicorn <app-name>.wsgi`
`echo python-2.7.11> runtime.txt`

PS: runtime.txt specifies the python version you are using, so set accordingly.

**Comment by saravanan-cm** [comment]
what was the solution for this issue?

**Comment by isdanni** [comment]
Wonder the same?

**Comment by frclasso** [comment]
the same problem here
