### ISSUE TITLE
Build failed at "Installing pip"

### ISSUE THREAD

**Issue by davegaeddert** [heroku/heroku-buildpack-python#664]
I'm fairly new to heroku, but my python app which was working fine yesterday is not deploying today. I noticed some pip-related changes here since then -- any chance the issue is related?

This is all I get for a build log:
```
-----> Python app detected
-----> Installing pip
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

Thanks in advance! (And let me know if I should take this kind of question somewhere else)

**Comment by portedison** [comment]
+1

**Comment by Benjamin-Dobell** [comment]
Does purging and then redeploying fix the issue?

https://github.com/heroku/heroku-buildpack-python/issues/661#issuecomment-374183119

**Comment by portedison** [comment]
Yes, that worked! Thanks Ben.

**Comment by kennethreitz** [comment]
this is fixed in master

**Comment by kennethreitz** [comment]
sorry for the hiccup!

**Comment by adamkgoldfarb** [comment]
Running into this issue again, purging the repo per Benjamin-Dobell and the other thread does not fix it. Any other ideas?

**Comment by ar1kumar** [comment]
Hi adamkgoldfarb, 

were you able to find a solution? I am still facing this issue. Updated the app from python 2.7.12 to 3.7.0
but the build fails at pip install. Tried purging the cache and removing and adding the buildpacks, nothing helped.
