### ISSUE TITLE
Cache unnecessarily being cleared due to lack of cached SQLite3 version file

### ISSUE THREAD

**Issue by luyizhao** [heroku/heroku-buildpack-python#909]
Post #907, we are no longer caching a `.heroku/python-sqlite3-version` version file and instead always running `sqlite3_install "$BUILD_DIR/.heroku/python"`. The missing version file causes builds now to unnecessarily clear their caches.

Because we no longer cache a `.heroku/python-sqlite3-version` version file, we are clearing all `.heroku` caches in https://github.com/heroku/heroku-buildpack-python/blob/v162/bin/steps/python#L72 because 
```bash
if [ -d .heroku/python ] && [ ! -f .heroku/python-sqlite3-version ] && python_sqlite3_check "$PYTHON_VERSION"; 
```
in https://github.com/heroku/heroku-buildpack-python/blob/v162/bin/steps/python#L70 will now always evaluate to true (for builds with caches and for python versions requiring sqlite3, i.e. where `python_sqlite3_check` is true).

I am actually not sure if the cache clearing logic https://github.com/heroku/heroku-buildpack-python/blob/v162/bin/steps/python#L67-L73 (originally introduced in #713) is still needed. If it isn't, a straightforward fix would be to remove those lines of cache-clearing logic. (Otherwise, we could still maintain a cached `.heroku/python-sqlite3-version` version file as we did before prior to #907)

Relatedly, the following related few lines from https://github.com/heroku/heroku-buildpack-python/pull/713 now appear to be outdated and can be removed now as well:
- https://github.com/heroku/heroku-buildpack-python/blob/v162/bin/compile#L169-L170
- https://github.com/heroku/heroku-buildpack-python/blob/v162/bin/steps/sqlite3#L62-L65

**Comment by sidmitra** [comment]
I'm wondering if this is the reason why builds were taking 25 mins on heroku CI. I had lxml, pandas, numpy and pip installing these was what was taking the bulk of the time. Our actual test run is only 3-4 mins whereas the test setup runs for ~25 mins.

```
...
       Running setup.py install for numpy: started
.           Running setup.py install for numpy: still running...
.           Running setup.py install for numpy: still running...
.           Running setup.py install for numpy: still running...
.           Running setup.py install for numpy: still running...
.           Running setup.py install for numpy: still running...
           Running setup.py install for numpy: finished with status 'done'
         Running setup.py install for pandas: started
.           Running setup.py install for pandas: still running...
.           Running setup.py install for pandas: still running...
..           Running setup.py install for pandas: still running...
..           Running setup.py install for pandas: still running...
.           Running setup.py install for pandas: still running...
.           Running setup.py install for pandas: still running...
.           Running setup.py install for pandas: still running...
.           Running setup.py install for pandas: still running...
.           Running setup.py install for pandas: still running...
           Running setup.py install for pandas: finished with status 'done'
...
```

**Comment by nikolaik** [comment]
Also getting:
```
Need to update SQLite3, clearing cache
```

This is slowing down deploys considerably.

**Comment by bmull** [comment]
Any progress here? Still happening for me.

**Comment by sktzofrenic** [comment]
Still an issue for me as well

**Comment by sktzofrenic** [comment]
Is there a work around that is available?

**Comment by sguichard** [comment]
> Is there a work around that is available?

I was able to fork the repo, comment out the offending lines, and add my fork as the Heroku buildpack without issue. I hope to switch back to the main branch once the problem is fixed, but in the meantime it significantly sped up my build times.

**Comment by CaseyFaist** [comment]
Hey y'all - thanks for reporting! This is the next item I'm working through, so hope to get some progress on it for y'all soon.

For anyone that's tried this linked pr (#915) - can you confirm if it worked for you? Command below:

`heroku buildpacks:set https://github.com/mz026/heroku-buildpack-python#fix-cache-clearing-due-to-sqlite3`

internal links:
https://heroku.support/829568

**Comment by sidmitra** [comment]
@CaseyFaist We're using the fork of PR #915 as our test buildpack to run the tests and it seems to work fine for that. It was only our heroku CI step that kept re-installing numpy, pandas, lxml and weren't caching this stuff. Our actual deploy was all the same. So we only updated the test build pack. After this our CI build step time went down by ~20 mins.

```
"environments": {
    "test": {
      ...
      "buildpacks": [
        {
          "url": "https://github.com/MyFork/heroku-buildpack-python.git"
        }
      ],
    },
...
}

**Comment by merwok** [comment]
The fix from #915 works for me!  Great to see caching back after all this time.

Two notes:

```
-----> Python app detected
 !     Python has released a security update! Please consider upgrading to python-3.8.1
       Learn More: https://devcenter.heroku.com/articles/python-runtimes
```
I am running with 3.8.2!

```
-----> SQLite3 has been installed before, skip it.
```
Why is there special handling for sqlite3?  Python requires zlib, bzlib, libmpdec, etc, why is sqlite3 singled out in messages and causing this whole problem?

**Comment by sktzofrenic** [comment]
I can confirm that #915 worked for me also. Thank you to those who managed a workaround, this has sped up my deploys to a manageable time.

**Comment by CaseyFaist** [comment]
Okay! See #925 for progress update - fix should be going out sometime this week 🎉 Thank you @mz026 for contributing #915 - I took a slightly different route to address the issue but your work highlighted problem areas and made my job easier on this one.

**Comment by CaseyFaist** [comment]
Fix has been merged and released! Please continue to report if you DON'T see your dependencies installing from cache after one redeploy (we have to get your cache set up, so it'll take 2 redeploys for you to see install from cache going into effect). Will leave this issue open for a bit to get more feedback.

**Comment by merwok** [comment]
This looks good for me (FTR I’m not using git deployment but `builds:create` command).

I am not seeing the false positive warning anymore (`Python has released a security update! Please consider upgrading to python-3.8.1`) :slightly_smiling_face: 

I would like to repeate my question:

Why is there special handling for sqlite3? Python makes use of zlib, bzlib, libmpdec, etc, why is sqlite3 singled out in messages and causing this whole problem?

**Comment by diedara** [comment]
Woah I am new to this. Well, still having the issue that it keeps re-installing the same things from the `requirements.txt`

**Comment by vsemionov** [comment]
It is definitely not fixed.

**Comment by merwok** [comment]
For some reason, cache is not working anymore for me:

```
-----> Python app detected
-----> Clearing cached dependencies
-----> Installing python-3.8.2
-----> Installing pip
-----> Installing SQLite3
Sqlite3 successfully installed.
-----> Installing requirements with pip
```

**Comment by walidthebest** [comment]
Hello 
I am still facing the same issue, dependencies are always re-install (this issue appears few days ago for the first time).
`
remote: -----> Python app detected
remote: -----> Clearing cached dependencies
remote: -----> Installing python-3.8.2
remote: -----> Installing pip
remote: -----> Installing dependencies with Pipenv 2018.5.18…
...
`

**Comment by sidmitra** [comment]
I can confirm this now as well. On our Heroku CI test run it clears all cache. Is the behaviour supposed to be different on test runs?

```-----> Fetching heroku/ci-postgresql buildpack...
       buildpack downloaded
-----> Fetching heroku/ci-redis buildpack...
       buildpack downloaded
-----> Fetching heroku/python buildpack...
       buildpack downloaded
-----> Postgresql app detected
       Using postgresql version: 12.2
       Using stack version: heroku-18
-----> Fetching and vendoring postgresql into slug
-----> Initializing database
       The files belonging to this database system will be owned by user "u6332".
       This user must also own the server process.
       
       The database cluster will be initialized with locale "en_US.UTF-8".
       The default text search configuration will be set to "english".
       
       Data page checksums are disabled.
       
       creating directory /app/.indyno/vendor/postgresql/data ... ok
       creating subdirectories ... ok
       selecting dynamic shared memory implementation ... posix
       selecting default max_connections ... 100
       selecting default shared_buffers ... 128MB
       selecting default time zone ... Etc/UTC
       creating configuration files ... ok
       running bootstrap script ... ok
       performing post-bootstrap initialization ... ok
       syncing data to disk ... ok
       
initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
       
       Success. You can now start the database server using:
       
           pg_ctl -D /app/.indyno/vendor/postgresql/data -l logfile start
       
       waiting for server to start.... done
       server started
       CREATE ROLE
-----> Copying .profile.d/00-pg-path.sh to add postgresql binaries to PATH
-----> Postgresql done
-----> Redis app detected
       Using redis version: 5.0.6
-----> Fetching redis from cache into slug
-----> Redis done
-----> Python app detected
-----> Clearing cached dependencies
-----> Installing python-3.7.6
-----> Installing pip
-----> Installing SQLite3
Sqlite3 successfully installed.
-----> Installing requirements with pip
```

**Comment by hfjallemark** [comment]
Can also confirm; app build seems to be working but CI builds still clears cache.

**Comment by boussouira** [comment]
Cache is cleared on every Heroku push
```
remote: -----> Build succeeded!
remote: -----> Python app detected
remote: -----> Clearing cached dependencies
remote: -----> Installing python-3.6.10
remote: -----> Installing pip
remote: -----> Installing SQLite3
remote: Sqlite3 successfully installed.
remote: -----> Installing requirements with pip
```

**Comment by mz026** [comment]
I got a working PR but it didn't get merged because the routes I took were somehow different. 
The [branch](https://github.com/mz026/heroku-buildpack-python/tree/fix-cache-clearing-due-to-sqlite3) is still alive, hope it can unblock you in the meantime. 😄 
https://github.com/heroku/heroku-buildpack-python/pull/915

**Comment by vsemionov** [comment]
I'm just wondering - does this affect all Python applications, or just some that meet certain conditions?

**Comment by nirzaf** [comment]
> It is still not using the cache.
> 
> Additionally, we started getting strange output during every deployment.
> 
> If the cache is clean (after `heroku builds:cache:purge`):
> 
> ```
> remote: -----> Python app detected
> remote: cp: cannot create regular file '/app/tmp/cache/.heroku/requirements.txt': No such file or directory
> ```
> 
> And then during the next deployments with upgraded dependencies:
> 
> ```
> remote: -----> Python app detected
> remote: 5d4
> remote: < awscli==1.18.36
> remote: 8,9c7,8
> remote: < boto3==1.12.36
> remote: < botocore==1.15.36
> remote: ---
> remote: > boto3==1.12.34
> remote: > botocore==1.15.34
> remote: 13c12
> remote: < certifi==2020.4.5
> remote: ---
> remote: > certifi==2019.11.28
> remote: 16,17c15
> remote: < colorama==0.4.3
> remote: < cryptography==2.9
> remote: ---
> ... and so on ...
> ```

I am getting the similar error as well

**Comment by boussouira** [comment]
Heroku is aware of this issue and this seem to be the upcoming fix #948

**Comment by johlym** [comment]
#948 was merged and deployed with https://github.com/heroku/heroku-buildpack-python/releases/tag/v169.
